# Generated by Django 4.0.2 on 2022-02-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='attempt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='guesses',
            field=models.JSONField(default={}),
        ),
    ]
