# Generated by Django 4.0.2 on 2022-02-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_alter_player_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lobby",
            name="code",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AlterField(
            model_name="lobby",
            name="word",
            field=models.CharField(default="", max_length=16),
        ),
    ]
