# Generated by Django 4.0.2 on 2022-02-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_attempt_game_ended_game_guesses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='guesses',
            field=models.JSONField(default=dict),
        ),
    ]
