# Generated by Django 4.0.2 on 2022-02-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_alter_player_lobby_alter_player_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lobby",
            name="code",
            field=models.CharField(default="none", max_length=8),
        ),
    ]
